support to insert datas with chunk to rocksdb
deepnova/tarim pull request #21
Opened 2023-03-23 08:42 UTC by wangpengfei2048

2023-03-23 09:21 UTC, deepzliu requested changes

2023-03-23 09:21 UTC, deepzliu commented on tarimdb/src/main/java/com/deepexi/tarimdb/DataNode.java
> +    private int port = 1303;
为什么需要改个端口？

2023-03-23 09:21 UTC, deepzliu commented on tarimdb/src/main/java/com/deepexi/tarimdb/tarimkv/KeyValueCodec.java
> +    public static KeyValueCodec KeyDecode(String internalKey, byte[] value) throws TarimKVException
这里用byte[]的话，会不会中间一些逻辑处理又要转成String?

2023-03-28 05:49 UTC, wangpengfei2048 commented on tarimdb/src/main/java/com/deepexi/tarimdb/DataNode.java
> +    private int port = 1303;
这里原来固定是启动第一个DataNode节点，在start()的方法中，启动
ServerBuilder builder = ServerBuilder.forPort(port);

2023-03-28 05:52 UTC, wangpengfei2048 commented on tarimdb/src/main/java/com/deepexi/tarimdb/tarimkv/KeyValueCodec.java
> +    public static KeyValueCodec KeyDecode(String internalKey, byte[] value) throws TarimKVException
这里使用byte和rocksdb格式一样，现在这里统一在connector里转换，value转成byte数组

2023-03-29 03:41 UTC, merged